### ISSUE TITLE
Add an "engines" field to package.json

### ISSUE THREAD

**Issue by travellingprog** [rtsao/babel-preset-es2015-node#1]
See https://docs.npmjs.com/files/package.json#engines

Would be good to use that field to explicitly state which version(s) of Node is/are supported.

Since you may not keep up with the maintenance of this preset, then "latest stable Node" is too vague to know what was the earliest version of Node you tested this on.

Also, it's a bit unclear if the LTS release of Node counts as "latest stable Node".

Thanks!

**Comment by rtsao** [comment]
Good idea with the engines field!

You might find chart at the bottom of https://github.com/nodejs/LTS is helpful.
