### ISSUE TITLE
Duplicate plugin for node4

### ISSUE THREAD

**Issue by sebakerckhof** [rtsao/babel-preset-es2015-node#4]
https://github.com/rtsao/babel-preset-es2015-node/blob/node4/index.js#L6

and

https://github.com/rtsao/babel-preset-es2015-node/blob/node4/index.js#L7

**Comment by sebakerckhof** [comment]
And I think it misses http://babeljs.io/docs/plugins/transform-es2015-spread/ according to https://nodejs.org/en/docs/es6/

**Comment by kintel** [comment]
I can confirm that this preset is broken for node 4. Adding the spread transform fixes it:

```
    require("babel-plugin-transform-es2015-spread"),
```

**Comment by rtsao** [comment]
Wow, nice catch! This must have been due to some oversight when merging... Sorry for the delay fixing this, somehow I missed this issue on GitHub. I've published `v4.0.1` which resolves the problem.
