### ISSUE TITLE
dIfferences with other similar packages

### ISSUE THREAD

**Issue by josmardias** [rtsao/babel-preset-es2015-node#5]
There are some packages for traspiling es2015 to node@6 out there:

https://github.com/rtsao/babel-preset-es2015-node (this repo)

```
    require("babel-plugin-transform-es2015-modules-commonjs"),
```

https://github.com/jhen0409/babel-preset-es2015-node6

```
    require('babel-plugin-transform-es2015-destructuring'),
    require('babel-plugin-transform-es2015-modules-commonjs'),
    require('babel-plugin-transform-es2015-function-name'),
```

https://github.com/Salakar/babel-preset-node6

```
    require('babel-plugin-syntax-trailing-function-commas'),
    require('babel-plugin-transform-es2015-modules-commonjs'),
```

This one [seems to be the mostly relied on](https://npmcompare.com/compare/babel-preset-es2015-node,babel-preset-es2015-node6,babel-preset-node,babel-preset-node6), but I'm pretty sure that import/export is not the only thing missing on node@6

Can you please evaluate these other two packages, and what is really missing here?
For example, [Function name property](http://node.green/#function--name--property) seems to be not working on node@6, and this package ignores it.

**Comment by graingert** [comment]
there's also michaelcontento/babel-preset-modern-node

https://npmcompare.com/compare/babel-preset-es2015-node,babel-preset-es2015-node6,babel-preset-modern-node,babel-preset-node,babel-preset-node6

**Comment by graingert** [comment]
@josmardias babel-preset-modern-node includes tests and support for all node versions.

**Comment by josmardias** [comment]
thanks @graingert , but the [6.x version on babel-preset-modern-node](https://github.com/michaelcontento/babel-preset-modern-node/blob/master/6.0.js) includes too much, so I'm not sure if it's the better alternative (besides the fact it's the only one with tests)

UPDATE:
seems that babel-preset-modern-node don't try to transpile ES2015 to node 6.x, instead, it tries to transpile staging features. So, it's not modular enough but seems to be a good package for "beyond ES2015" needs.

**Comment by graingert** [comment]
@josmardias the maintainer,  @michaelcontento, wants to make the stage-0 features optional (see 
https://github.com/michaelcontento/babel-preset-modern-node/pull/43) have a look at https://github.com/michaelcontento/babel-preset-modern-node/pull/46 for the new approach.

**Comment by graingert** [comment]
@josmardias:

in conclusion you need:

``` js
    require('babel-plugin-transform-es2015-destructuring'),
    require('babel-plugin-transform-es2015-modules-commonjs'),
    require('babel-plugin-transform-es2015-function-name'),
```

**Comment by rtsao** [comment]
I was just referencing the kangax table (which says destructuring and function name properties are supported natively in Node 6.0):

http://node.green/#destructuring--declarations
http://node.green/#destructuring--parameters
http://node.green/#function--name--property

**Comment by graingert** [comment]
They are missing 'iterator closing' see my tests in that repo
On 28 Apr 2016 19:13, "Ryan Tsao" notifications@github.com wrote:

I was just referencing the kangax table (which says destructuring and
function name properties are supported natively in Node 6.0):
http://node.green/

http://node.green/#destructuring--declarations
http://node.green/#destructuring--parameters
http://node.green/#function--name--property

**Comment by michaelcontento** [comment]
Yes, tomorrow I'll release v2.0.0 of [modern-node](https://github.com/michaelcontento/babel-preset-modern-node) which drops all <stage-4 extensions. In the end it should be a safe bet for "I want to write modern node with as less transpilation as possible" 😎

**Comment by rtsao** [comment]
Per https://github.com/rtsao/babel-preset-es2015-node/pull/6, this preset now automatically checks which version of Node is being used. So this preset is now has a larger scope than a preset for specific version of node, so the code is definitely going to be different.

For any issues (e.g. missing plugins) for a given version of node, feel free to open a new issue or submit a PR! 😄
